platform :ios, '7.0' 
pod 'MBProgressHUD', '~> 0.9.1'
pod 'JSONKit', '~> 1.4'
pod 'ViewDeck', '~> 2.3.1'
pod 'IQKeyboardManager', '~> 3.3.0'
pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage-Category', '~> 1.4'
